export const CHANGE_GLOBAL_SETTINGS = 'CHANGE_GLOBAL_SETTINGS';

export const CATEGORY_CHANGE_SELECTION = 'CATEGORY_CHANGE_SELECTION';

export const TOP_SALES_REQUEST = 'TOP_SALES_REQUEST';
export const TOP_SALES_FAILURE = 'TOP_SALES_FAILURE';
export const TOP_SALES_SUCCESS = 'TOP_SALES_SUCCESS';

export const CATALOG_ITEMS_RECIEVED_COUNT = 'CATALOG_ITEMS_RECIEVED_COUNT';
export const CATALOG_REQUEST = 'CATALOG_REQUEST';
export const CATALOG_FAILURE = 'CATALOG_FAILURE';
export const CATALOG_SUCCESS = 'CATALOG_SUCCESS';

export const IMAGES_REQUEST = 'IMAGES_REQUEST';
export const IMAGES_FAILURE = 'IMAGES_FAILURE';
export const IMAGES_SUCCESS = 'IMAGES_SUCCESS';
export const IMAGES_SET_SHOW_INDEX = 'IMAGES_SET_SHOW_INDEX';
